# Name of the application.
applicationName: app-test

# pulumi:
#   acmCertArn: value-from-pulumi
#   awsAccountId: value-from-pulumi
#   awsRegion: value-from-pulumi
#   domainBase: value-from-pulumi
#   envName: value-from-pulumi
#   route53ZoneId: value-from-pulumi
#   svcAcctName: value-from-pulumi

deployment:
  enabled: true
  image:
    repository: traefik/whoami
    tag: latest
    pullPolicy: Always

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - '{{ template "base.name" . }}'

  startupProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 100
    timeoutSeconds: 5
    httpGet:
      port: http
      path: /healthz

  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 100
    timeoutSeconds: 5
    httpGet:
      port: http
      path: /readyz

  livenessProbe:
    enabled: false
    failureThreshold: 2
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 2
    initialDelaySeconds: 10
    httpGet:
      port: http
      path: /livez

  resources:
    limits:
      memory: 3Gi
      cpu: 512m
      ephemeral-storage: 2Gi
    requests:
      memory: 512Mi
      cpu: 256m
      ephemeral-storage: 1Gi

  ports:
    - containerPort: 8080
      name: http
      protocol: TCP

rbac:
  enabled: true

  serviceAccount:
    enabled: true
