# https://pre-commit.com/#pre-commit-configyaml---hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: lint-charts
        name: Lint All Charts
        entry: ./.ci/ct.sh
        language: script
        pass_filenames: false
      - id: test-app
        name: Unit Tests charts/app
        entry: ./.ci/helm-unittest.sh
        args: [charts/app]
        language: script
        pass_filenames: false
  - repo: https://github.com/norwoodj/helm-docs
    rev: ""
    hooks:
      - id: helm-docs-container
        entry: jnorwood/helm-docs:latest
        args:
          # Make the tool search for charts only under the `charts` directory
          - --chart-search-root=charts
