---
apiVersion: v2
name: app
description: Generic application chart
type: application
version: 0.1.0
kubeVersion: ">=1.29.0-0"
home: https://github.com/andreswebs-public-images/helm-charts
sources:
  - https://github.com/andreswebs-public-images/helm-charts
keywords:
  - application
  - deployment
  - generic
maintainers:
  - name: andreswebs
    url: https://github.com/andreswebs
