{{- define "base.externalsecret" -}}
{{- range $nameSuffix, $data := .Values.externalSecret.files }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "base.name" $ }}-{{ $nameSuffix }}
  namespace: {{ include "base.namespace" $ }}
  labels:
  {{- include "base.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.externalSecret.refreshInterval | default "1h" }}
{{- if and (not $data.data) (not $data.dataFrom) }}
{{- fail "Data or datafrom not specified for secret {{ template 'base.name' $ }}-{{ $nameSuffix }} " }}
{{- end }}
{{- if $data.data }}
  data:
{{- range $secretKey, $remoteRef := $data.data}}
    - secretKey: {{ $secretKey }}
{{ toYaml $remoteRef | indent 6}}
{{- end }}
{{- end }}
{{- if $data.dataFrom }}
  dataFrom:
    - extract:
        key: "/{{ $.Values.pulumi.envName}}/{{ $data.dataFrom.key }}"
{{- end }}
  {{- if $data.secretStore }}
  secretStoreRef:
    name: "{{ $data.secretStore.name }}-{{ .Values.pulumi.awsRegion }}"
    kind: {{ $data.secretStore.kind | default "ClusterSecretStore" }}
  {{- else }}
  secretStoreRef:
    name: "{{ $.Values.externalSecret.secretStore.name }}-{{ $.Values.pulumi.awsRegion }}"
    kind: {{ $.Values.externalSecret.secretStore.kind | default "ClusterSecretStore" }}
  {{- end}}
  target:
    name: {{ template "base.name" $ }}-{{ $nameSuffix }}
    template:
      type: {{ $data.type | default "Opaque" }}
{{- if or $data.annotations $data.labels}}
      metadata:
{{- if $data.annotations }}
        annotations:
{{ toYaml $data.annotations | indent 10 }}
{{- end }}
{{- if $data.labels }}
        labels:
{{ toYaml $data.labels | indent 10 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
