# yaml-language-server: $schema=../values.schema.json
---
image:
  repository: traefik/whoami
  tag: v1.11.0

deployment:
  replicas: 3

networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: '{{ include "app.name" . }}'
