{{- define "base.app" -}}

{{- if (.Values.deployment).enabled }}
{{ include "base.deployment" . }}
{{- end }}

{{- if and (.Values.autoscaling).enabled (.Values.deployment).enabled }}
{{ include "base.hpa" . }}
{{- end }}

{{- if (.Values.service).enabled }}
{{ include "base.service" . }}
{{- end }}

{{- if (.Values.ingress).enabled -}}
{{ include "base.ingress" . }}
{{- end }}

{{- if (.Values.networkPolicy).enabled }}
{{ include "base.networkpolicy" . }}
{{- end }}

{{- if or (.Values.pdb).minAvailable (.Values.pdb).maxUnavailable | and (.Values.pdb).enabled }}
{{ include "base.pdb" . }}
{{- end }}

{{- if (.Values.externalSecret).enabled }}
{{ include "base.externalsecret" . }}
{{- end }}

{{- if and (.Values.rbac).enabled .Values.rbac.serviceAccount.enabled }}
{{ include "base.serviceaccount" .}}
{{- end }}

{{- end }}
