{{- define "base.pdb" -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "base.labels" . | nindent 4 }}
  name: {{ template "base.name" . }}
  namespace: {{ include "base.namespace" . }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
{{- end }}
