{{- define "base.service" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "base.name" . }}
  namespace: {{ template "base.namespace" $ }}
  labels:
  {{- include "base.labels" . | nindent 4 }}
  {{- if .Values.service.additionalLabels }}
    {{- toYaml .Values.service.additionalLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- include "base.tplvalues.render" ( dict "value" .Values.service.annotations  "context" $ ) | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
{{- end }}
{{- if eq .Values.service.type "LoadBalancer" }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
{{ include "base.selectorLabels" . | indent 4 }}
{{- if .Values.deployment.podLabels }}
{{ toYaml .Values.deployment.podLabels | indent 4 }}
{{- end }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
{{- end }}
