{{- if .Values.ingress.enabled }}
{{- if not .Values.ingress.httpHosts }}
{{- fail "ingress.httpHosts must be set when ingress.enabled is true" }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.metadata.labels" (dict "extra" .Values.ingress.labels "context" $) | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- include "app.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- range . }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- with .secretName }}
      secretName: {{ . | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.httpHosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "app.fullname" $ }}
                port:
                  number: {{ .servicePortNumber }}
          {{- end }}
    {{- end }}
{{- end }}
