{{- if .Values.networkPolicy.enabled }}
{{- if not (or .Values.networkPolicy.ingress .Values.networkPolicy.egress) }}
{{- fail "at least one of networkPolicy.ingress or networkPolicy.egress must be set" }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.metadata.labels" (dict "extra" .Values.networkPolicy.labels "context" $) | nindent 4 }}
  {{- with .Values.networkPolicy.annotations }}
  annotations:
    {{- include "app.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress }}
    - Egress
    {{- end }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- include "app.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- include "app.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
{{- end }}
