{{- if and .Values.pdb (eq .Values.pdb.enable true) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not (or .Values.pdb.minAvailable .Values.pdb.maxUnavailable) }}
  {{- fail "Either pdb.minAvailable or pdb.maxUnavailable must be defined" }}
  {{- end }}
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
{{- end }}
