{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccountName" . }}
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.metadata.labels" (dict "extra" .Values.serviceAccount.labels "context" $) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- include "app.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
