{{- if .Values.service.enabled }}
{{- if not .Values.service.ports }}
{{- fail "service.ports must be set when service.enabled is true" }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.metadata.labels" (dict "extra" .Values.service.labels "context" $) | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- include "app.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    {{- include "app.tplvalues.render" (dict "value" .Values.service.ports "context" $) | nindent 4 }}
{{- end }}
