---
name: Helm Chart CI

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  charts:
    strategy:
      matrix:
        charts:
          - app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Helm chart
        env:
          OCI_REGISTRY: oci://${{ steps.ecr-login.outputs.registry }}/helm
          CHART: ${{ matrix.charts }}
        run: |
          helm package ./charts/${CHART}
          helm push "${CHART}"-*.tgz "${OCI_REGISTRY}"
