---
name: Helm Chart CI

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  helm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Helm chart
        env:
          OCI_REGISTRY: oci://${{ steps.ecr-login.outputs.registry }}/helm
          CHART_VERSION: 0.0.1
        run: |
          helm package ./charts/app
          helm push "app-${CHART_VERSION}.tgz" "${OCI_REGISTRY}"
