---
name: Helm Chart CI

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  helm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Helm chart
        env:
          OCI_REGISTRY: oci://${{ steps.ecr-login.outputs.registry }}/helm
          OCI_REPO_NAME: app
        run: |
          helm package ./charts/app
