---
name: Helm Chart CI

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  helm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: stable

      - name: Helm Template
        run: helm template ./charts/app.test
