---
name: Helm Chart CI

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  charts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        charts:
          - app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Environment
        env:
          REGISTRY_BASE: ${{ steps.ecr-login.outputs.registry }}
          REGISTRY_ALIAS: ${{ vars.AWS_ECR_PUBLIC_ALIAS }}
          CHART_NAME: ${{ matrix.charts }}
          CHART_PATH: ./charts/${{ matrix.charts }}
        run: |
          OCI_REGISTRY="oci://${REGISTRY_BASE}/${REGISTRY_ALIAS}/charts"
          echo "OCI_REGISTRY=${OCI_REGISTRY}" >> $GITHUB_ENV
          echo "CHART_NAME=${CHART_NAME}" >> $GITHUB_ENV
          echo "CHART_PATH=${CHART_PATH}" >> $GITHUB_ENV

      - name: Push Helm chart
        run: |
          [ -d "${CHART_PATH}/charts" ] && rm -rf "${CHART_PATH}/charts"
          [ -f "${CHART_PATH}/Chart.lock" ] && rm -f "${CHART_PATH}/Chart.lock"
          helm dependency build "${CHART_PATH}"
          helm package "${CHART_PATH}"
          helm push "${CHART_NAME}"-*.tgz "${OCI_REGISTRY}"
