---
name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: python -m pip install pre-commit
        shell: bash
      - run: python -m pip freeze --local
        shell: bash
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
        shell: bash

  diff:
    runs-on: ubuntu-latest
    needs: [pre-commit]
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Helm Template
        run: |
          helm dependency build ./charts/app.test
          helm template ./charts/app.test | tee source.k8s.yaml

      - name: Upload source.k8s.yaml artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-k8s
          path: source.k8s.yaml

      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Download source.k8s.yaml artifact
        uses: actions/download-artifact@v4
        with:
          name: source-k8s

      - name: Helm Template
        run: |
          helm dependency build ./charts/app.test
          helm template ./charts/app.test | tee target.k8s.yaml

      - name: Diff
        run: |
          diff source.k8s.yaml target.k8s.yaml | tee diff.txt

      - name: Report
        uses: andreswebs/gh-actions/.github/actions/file-report@main
        with:
          source-txt-file: diff.txt
          environment: test
